### PR TITLE
Add tests and implementation for suggest_grade_adjustment function

### PR DESCRIPTION
**Pull request by tdkhanhvu**
- Check for input type to be correct (string for `course_id`, float or int for 3 benchmarks
- Check the range of the benchmarks: between 0 and 100
- Adjust the grade in terms of labs, quizzes and overall courses (by adjusting each component)
- Add tests for all above scenarios

### CODE REVIEW

**Review by jraza19 — COMMENTED** [review]
Thanks @tdkhanhvu ! Great work. I wanted to ask about the purpose of this tracker = generate_input_suggest_grade_adjustment() - what is this doing? Also, the last three functions to me dont seem to belong in test file. if you could clarify where these get used. Lastly, there is no data at the moment but when i tried to run your code through poetry run pytest. it results in filenotfounderror.

**Comment by tdkhanhvu** [comment]
> Thanks @tdkhanhvu ! Great work. I wanted to ask about the purpose of this tracker = generate_input_suggest_grade_adjustment() - what is this doing? Also, the last three functions to me dont seem to belong in test file. if you could clarify where these get used. Lastly, there is no data at the moment but when i tried to run your code through poetry run pytest. it results in filenotfounderror.

The `generate_input_suggest_grade_adjustment` method will generate the dummy input data to test the `suggest_grade_adjustment` method. It will have 1 course and 1 student only. I'm using this as it is easier to verify that my method is working correctly compared to the toy data set. The reason why we need the toy data set for other functions is because you need to rank and calculate quantiles, so you need to have a few courses and few students to demonstrate that. Ideally, I can create new test cases for 2 courses or more and 2 students or more, but let's just put the simplest case here first to make sure that they work.

Similar to above, the last 3 functions are helper functions to generate the data. It is easier than I have to copy and paste the same thing for each test case.

Can you paste the error here?

**Comment by jraza19** [comment]
> > Thanks @tdkhanhvu ! Great work. I wanted to ask about the purpose of this tracker = generate_input_suggest_grade_adjustment() - what is this doing? Also, the last three functions to me dont seem to belong in test file. if you could clarify where these get used. Lastly, there is no data at the moment but when i tried to run your code through poetry run pytest. it results in filenotfounderror.
> 
> The `generate_input_suggest_grade_adjustment` method will generate the dummy input data to test the `suggest_grade_adjustment` method. It will have 1 course and 1 student only. I'm using this as it is easier to verify that my method is working correctly compared to the toy data set. The reason why we need the toy data set for other functions is because you need to rank and calculate quantiles, so you need to have a few courses and few students to demonstrate that. Ideally, I can create new test cases for 2 courses or more and 2 students or more, but let's just put the simplest case here first to make sure that they work.
> 
> Similar to above, the last 3 functions are helper functions to generate the data. It is easier than I have to copy and paste the same thing for each test case.
> 
> Can you paste the error here?

Understood - issue resolved by doing poetry install first. 

image

**Review by jraza19 — APPROVED** [review]
The changes have been reviewed and tested locally with succession.

**Pull request merged**
